blog/urls.py
from django.urls import path, re_path
from blog import views


app_name = 'blog'
urlpatterns = [

    # Example: /blog/
    path('', views.PostLV.as_view(), name='index'),

    # Example: /blog/post/ (same as /blog/)
    path('post/', views.PostLV.as_view(), name='post_list'),

    # Example: /blog/post/django-example/
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),

    # Example: /blog/archive/
    path('archive/', views.PostAV.as_view(), name='post_archive'),

    # Example: /blog/archive/2019/
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),

    # Example: /blog/archive/2019/nov/
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),

    # Example: /blog/archive/2019/nov/10/
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),

    # Example: /blog/archive/today/
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),

    # Example: /blog/tag/
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),

    # Example: /blog/tag/tagname/
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),

    # Example: /blog/search/
    path('search/', views.SearchFormView.as_view(), name='search'),

    # Example: /blog/add/
    path('add/',
         views.PostCreateView.as_view(), name="add",
    ),

    # Example: /blog/change/
    path('change/',
         views.PostChangeLV.as_view(), name="change",
    ),

    # Example: /blog/99/update/
    path('<int:pk>/update/',
         views.PostUpdateView.as_view(), name="update",
    ),

    # Example: /blog/99/delete/
    path('<int:pk>/delete/',
         views.PostDeleteView.as_view(), name="delete",
    ),
]

forum/urls.py
from django.urls import path
from . import views
import forum.views

app_name='forum'
urlpatterns = [
    path('', views.forum_home, name='home'),
    path('new/', views.new, name='new'),
    path('detail/<int:forum_id>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('postcreate/', views.postcreate, name='postcreate'),
    path('update/<int:forum_id>/', views.update, name='update'),
    path('delete/<int:forum_id>/', views.delete, name='delete'),
    path('search', views.search, name='search'),
]

mate/urls.py
from django.urls import path

from mate import views

app_name = 'mate' 
urlpatterns = [
    path('', views.mate_home, name="home"),
    path('gallery', views.gallery, name="gallery"),
    path('quest', views.quest, name="quest"),
    path('questdone/<int:quest_id>', views.quest_done, name="quest-done"),
    path('upload/', views.upload, name='upload'),
	path('message/', views.send_message, name='send_message'),
]

moodtracker/urls.py
from django.urls import path

from moodtracker import views

app_name = 'moodtracker'
urlpatterns = [    
	path('', views.write_record, name='home'),
	path('record/<int:record_id>', views.view_record, name='view'), 
	path('write/', views.write_record, name='write'),
    path('create/',views.create_record, name='create'),
    path('analysis/', views.analysis, name='analysis'),
]

myprofile/urls.py
from django.urls import path

from myprofile import views

app_name = 'myprofile'
urlpatterns = [
    path('', views.profile_home, name='home'),
    path('detail/<int:profile_id>', views.profile_detail, name='detail'),
    path('upload/', views.upload, name='upload'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

import myprofile.views
import forum.views
import moodtracker.views
import mate.views
import therapy.views

from mysite import views
from mysite.views import HomeView, UserCreateView, UserCreateDoneTV


urlpatterns = [
    path('admin/', admin.site.urls),
    # shkim
    path('accounts/', include('django.contrib.auth.urls')), 
    path('accounts/register/', UserCreateView.as_view(), name='register'), 
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),

    path('', views.main, name='main'),
    path('student_analysis/<int:person_id>', views.student_analysis, name='student_analysis'),
    
    path('blog/', include('blog.urls')),
    path('forum/',include('forum.urls')),
    path('myprofile/',include('myprofile.urls'), name='myprofile'),
    path('moodtracker/', include('moodtracker.urls'), name='moodtracker'),
    path('mate/',include('mate.urls'), name='mate'),
    path('therapy/', include('therapy.urls'), name='therapy'),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

therapy/urls.py
from django.urls import path
from therapy import views

app_name = 'therapy'
urlpatterns = [
    path('', views.therapy, name='therapy'),
    path('result/', views.result, name='result'),
]

moodtracker/models.py
from django.db import models
from django.contrib.auth.models import User

class MoodTracker(models.Model):
    username = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='USERNAME', blank=True, null=True) # User 모델과 연결
    content = models.CharField(max_length=800) # 최대 800자
    pub_date = models.DateTimeField(auto_now=True)
    pub_date_year = models.CharField(max_length=10, default=0)
    pub_date_month = models.CharField(max_length=10, default=0)
    pub_date_day = models.CharField(max_length=10, default=0)
    mood = models.CharField(max_length=15)
    pos_neg = models.IntegerField(default=0)
    
    images = models.ImageField(blank=True, upload_to="images", null=True)
    anger = models.FloatField(default=0)
    contempt = models.FloatField(default=0)
    disgust = models.FloatField(default=0)
    fear = models.FloatField(default=0)
    happiness = models.FloatField(default=0)
    neutral = models.FloatField(default=0)
    sadness = models.FloatField(default=0)
    surprise = models.FloatField(default=0)
    #timeout = models.IntegerField(default=0)

    def __str__(self):
        return "%s - %s" % (self.username, self.pub_date) # 유저와 날짜로 구분

class Wordcloud(models.Model):
    username = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='USERNAME', blank=True, null=True)
    wc_image = models.ImageField(upload_to='')


    '''
        테스트 데이터
        자꾸 짜증나게 말을 하는 친구가 있다. 우리 반 대신 다른 반으로 가고 싶다. 담임 선생님이 나를 안좋아한다. 담임이 자꾸 나만 혼낸다. 담임이 성적 떨어졌다고 혼냈다. 담임이 교무실에서 혼냈다.
        부정적인 리뷰
        정확도 : 90.238
        angry

        엄마랑 오랜만에 쇼핑을 가서 옷도 사고 신발도 샀다. 공부로부터 벗어나서 재밌게 노니까 행복했다.
        긍정적인 리뷰
        정확도 : 95.094
        happy

        야자를 땡땡이 치려다가 선생님한테 걸려서 혼났다. 떡볶이가 너무 땡겼는데...
        부정적인 리뷰
        정확도 : 53.908
        sad

        자전거를 타고 한강 주변을 돌았다. 날씨가 습해서 개운하진 않았다. 집에 와서 샤워하고 아빠가 사오신 딸기우유를 마셨다.
        긍정적인 리뷰
        정확도 : 84.671
        soso

        카페에서 내가 좋아하는 오레오 케이크를 먹으며 공부하고 친구들과 수다떨었다. 사실 공부는 많이 안 했지만 스트레스가 풀렸다.
        긍정적인 리뷰
        정확도 : 92.208
        calm
    '''

moodtracker/views.py
from django.shortcuts import render, redirect
from django.utils import timezone
import random

from django.views import generic

from .models import MoodTracker, Wordcloud
from django.contrib.auth.models import User

import pickle
from konlpy.tag import Okt
import nltk

from wordcloud import WordCloud
from wordcloud import STOPWORDS
import matplotlib.pyplot as plt

import requests
from io import BytesIO
from PIL import Image, ImageDraw
import cognitive_face as CF

from django.contrib.auth.decorators import login_required

# 작성된 감정 일기 보는 화면으로 이동
@login_required
def view_record(request, record_id):
    user = request.user
    records = MoodTracker.objects.filter(username=user) # 유저의 모든 감정 일기 기록
    sp_record = MoodTracker.objects.get(pk=record_id) # 요청받은 감정 일기 1개

    

    item = {
        'records': records,
        'sp_record': sp_record,
    }
    return render(request, 'moodtracker/moodtracker_record.html', item)


# 인식된 얼굴에 네모 박스 그리는 함수 작성
def getRectangle(faceDictionary):
    rect = faceDictionary['faceRectangle']
    left = rect['left']
    top = rect['top']
    bottom = left + rect['height']
    right = top + rect['width']
    return ((left, top), (bottom, right))



# 감정 일기 분석 화면으로 이동
@login_required
def analysis(request):
    user = request.user
    moodtrackers = MoodTracker.objects.filter(username=user) # 현재 사용자와 일치하는 정보만 불러온다
    rec_pos_per = recent_pos_neg(user)
    recent_mood, saying = recent_mood_text(rec_pos_per, user) # 요즘 기분 text, 명언 text
    pos_per, neg_per = pos_neg_percent(moodtrackers) # 긍정 부정 개수 구하기 (날짜 조건 걸어야 함)
    happy, sad, calm, angry, soso = mood_num(moodtrackers) # 감정 개수 구하기
    mft1, mft2, mft3 = create_wordcloud(moodtrackers, user) # 워드 클라우드 생성, 빈출 높은 단어 가져온다.
    wc = Wordcloud.objects.get(username=user) # 워드 클라우드 객체 가져오기

    item = {
        'pos_per' : pos_per,
        'neg_per' : neg_per,
        'happy' : happy,
        'sad' : sad,
        'calm' : calm,
        'angry' : angry,
        'soso' : soso,
        'wc' : wc,
        'moodtrackers' : moodtrackers,
        'user' : user,
        'mft1' : mft1,
        'mft2' : mft2,
        'mft3' : mft3,
        #'rec_pos_per' : rec_pos_per,
        #'rec_neg_per' : rec_neg_per,
        'recent_mood' : recent_mood,
        'saying' : saying,
    }

    return render(request, 'moodtracker/moodtracker_analysis.html', item)


# 감정 일기 쓰는 페이지로 이동
@login_required
def write_record(request):
    user = request.user
    records = MoodTracker.objects.filter(username=user)
    year = timezone.datetime.now().year
    month = timezone.datetime.now().month
    day = timezone.datetime.now().day
    item = {
        'records' : records,
        'year' : year,
        'month' : month,
        'day' : day,
    }
    return render(request, 'moodtracker/moodtracker_write.html', item)


# Analysis - 긍정, 부정 비율 구하기
def pos_neg_percent(moodtrackers):
    pos=neg=0

    for record in moodtrackers:
        if record.pos_neg == 0:
            neg+=1
        else:
            pos+=1
    
    if pos == 0:
        pos_per = 0 # 0일 경우 zero division error 방지
    else:
        pos_per = round(pos/(pos+neg)*100, 1) # XX.X% 반환
    
    if neg == 0:
        neg_per = 0 # 0일 경우 zero division error 방지
    else:
        neg_per = round(neg/(pos+neg)*100, 1) # XX.X% 반환

    return pos_per, neg_per

# Analysis - 최근 10개 일기의 긍정, 부정 비율
def recent_pos_neg(user):
    recent_ten = MoodTracker.objects.filter(username=user).order_by("-id")[:7]
    pos=neg=0 # 10개 미만일 때 총 개수 세기 위해 neg도 센다.
    for record in recent_ten:
        if record.pos_neg == 1:
            pos+=1
        else:
            neg+=1
    
    if pos == 0:
        pos_per = 0 # 0일 경우 zero division error 방지
    else:
        pos_per = round(pos/(pos+neg)*100, 1) # XX.X% 반환
    
    return pos_per

# Analysis - 요즘 기분 text, 명언 text
def recent_mood_text(rec_pos_per, user):
    if rec_pos_per >= 0 and rec_pos_per <= 20 :
        text = '요즘 스트레스를 받는 일이 있나요? 혹시 우울감을 느낀다면 선생님이나 전문가에게 도움을 받아보는 건 어떨까요?'
        saying = '길을 잃는 다는 것은 곧 길을 알게 된다는 것이다. –동아프리카속담'
    elif rec_pos_per <= 40 :
        text = '요즘 기분이 상할 만한 일이 있었나 봐요. 친구들과의 대화, 혼자만의 시간, 상담 등을 통해 몸과 마음을 재충전하는 걸 추천해 드려요.'
        saying = '겨울이 오면 봄이 멀지 않으리. -셸리'
    elif rec_pos_per <= 60 :
        text = '기분이 좋았던 날도, 안 좋았던 날도 있었네요. '+str(user)+'님의 하루가 매일매일 즐겁길 바래요!'
        saying = '만족하게 살고 때때로 웃으며 많은 사람을 사랑한 삶이 성공한다. - 스탠리'
    elif rec_pos_per <= 80 : 
        text = str(user)+'님의 요즘은 좋은 일이 많았군요! 앞으로 속상한 일이 생겨도 '+str(user)+'님은 잘 헤쳐나갈 수 있을 거예요. 그렇지만 도움이 필요하다면 언제든지 말해주세요.'
        saying = '오랫동안 꿈을 그리는 사람은 마침내 그 꿈을 닮아 간다. -앙드레 말로'
    elif rec_pos_per <= 100 : 
        text = '긍정의 기운이 가득한 요즘! 만족스러운 일상을 보내고 있나요? '+str(user)+'님의 일상이 더욱 즐거운 일들로 가득했으면 좋겠어요. 도움이 필요하다면 언제든지 말해주세요.'
        saying = '언제나 현재에 집중할 수 있다면 행복할 것이다. -파울로 코엘료'
    else:
        text = '텍스트 불러오기 오류'
        saying = '명언 불러오기 오류'
    return text, saying

# Analysis - 감정 개수 구하기
def mood_num(moodtrackers):
    happy=sad=calm=angry=soso = 0

    for record in moodtrackers:
        if record.mood == 'happy':
            happy+=1
        elif record.mood == 'sad':
            sad+=1
        elif record.mood == 'calm':
            calm+=1
        elif record.mood == 'angry':
            angry+=1
        else :
            soso+=1
    return happy, sad, calm, angry, soso

# Analysis - 워드 클라우드 생성
def create_wordcloud(moodtrackers, user):
    # 이전 워드클라우드 모델에서 삭제
    instance = Wordcloud.objects.filter(username=user) 
    instance.delete()
    
    content_text = ''
    for record in moodtrackers:
        content_text = content_text + record.content
    
    okt = Okt()
    tokens_ko = okt.morphs(content_text)

    stopwords = ['안', '나', '내', '나는', '나를', '내가', '너무', '없다', '정말', '것은', '있다.', '자꾸', '싶지', '않다', '같다', '싶다', '했다', '나왔다', '.', '이', '가', '을', '에', '를', '는', '들', '은', '이다', '것', '거', '에서', '했다', '다', '도', '하는', '만', '한테', '한', '수', '게', '랑', '한다', '하고', '?', '이랑', '싶다', '의', '으로',
              '요', '로', '으로', ',', ]

    tokens_ko = [each_word for each_word in tokens_ko
             if each_word not in stopwords]
    ko = nltk.Text(tokens_ko)
    most_freq_text = ko.vocab().most_common(3)

    wordcloud = WordCloud(font_path='moodtracker/static/fonts/AppleSDGothicNeoSB.ttf', background_color='white', stopwords=stopwords, width=500, height=500).generate_from_text(content_text)
    filename1 = 'media/%s_wc.png' % user
    filename2 = '%s_wc.png' % user 
    wordcloud.to_file(filename1)
    '''
    plt.figure(figsize=(400,400)) #이미지 사이즈 지정
    plt.imshow(wordcloud)
    plt.axis("off") #x y 축 숫자 제거
    plt.show()
    '''
    wc = Wordcloud() # 워드클라우드 객체 하나 생성
    wc.username = user 
    wc.wc_image = filename2 
    wc.save() # 데이터베이스에 저장

    mft1 = most_freq_text[0][0]
    mft2 = most_freq_text[1][0]
    mft3 = most_freq_text[2][0] 
    return mft1, mft2, mft3


def tokenizer(text):
    okt = Okt()
    return okt.morphs(text)

# 작성 내용을 모델에 돌려서 긍정/부정 결과 얻는다.
# !!계속 오류나는 중.
def use_model(content):
    with open('static/pipe.dat', 'rb') as fp:
        pipe = pickle.load(fp)
    
    import numpy as np

    str = [content]
    #r1 = np.max(pipe.predict_proba(str)*100) # 예측 정확도
    r2 = pipe.predict(str)[0] # 예측 결과

    if r2 == '1' :
        pos_neg = 1 # 긍정
    else :
        pos_neg = 0 # 부정
    
    return pos_neg


# MoodTracker 일기 내용 저장 & 긍정부정 모델 돌려서 결과 같이 저장
def create_record(request):
    user = request.user

    year = timezone.datetime.now().year
    month = timezone.datetime.now().month
    day = timezone.datetime.now().day

    content = request.POST['content']

    mood_record = MoodTracker()
    mood_record.username = user
    mood_record.content = content
    mood_record.mood = request.POST['mood'] 
    mood_record.pub_date = timezone.datetime.now()
    mood_record.pub_date_year = year
    mood_record.pub_date_month = month
    mood_record.pub_date_day = day

    images = request.FILES['images']
    
    emotion = {}

    emotion = find_emotion(images, user, year, month, day) # 해당 감정 일기
    emotion = emotion[0]
    mood_record.anger = round(emotion['emotion']['anger']*100, 1)
    mood_record.contempt = round(emotion['emotion']['contempt']*100, 1)
    mood_record.disgust = round(emotion['emotion']['disgust']*100, 1)
    mood_record.fear = round(emotion['emotion']['fear']*100, 1)
    mood_record.happiness = round(emotion['emotion']['happiness']*100, 1)
    mood_record.neutral = round(emotion['emotion']['neutral']*100, 1)
    mood_record.sadness = round(emotion['emotion']['sadness']*100, 1)
    mood_record.surprise = round(emotion['emotion']['surprise']*100, 1)
    
    filename2 = '%s_face_%s_%s_%s.png' % (user, year, month, day)

    mood_record.images = filename2

    pos_neg = use_model(content)
    mood_record.pos_neg = pos_neg    

    mood_record.save()
    return redirect('/moodtracker/record/'+str(mood_record.id)) # '/moodtracker/' + +str(mood_record.id)

def find_emotion(images, user, year, month, day):
    KEY = '66b40727db3b42b2a07497598b032d19' # 자신의 Cognitive Services API KEY
    CF.Key.set(KEY)

    BASE_URL = 'https://eastus.api.cognitive.microsoft.com/face/v1.0/' # 자신의 지역에 해당하는 URL
    CF.BaseUrl.set(BASE_URL)

    img_url = images #'face_image.jpg' # 이미지 파일의 경로
    faces = CF.face.detect(img_url,True,False,'emotion') # 중요!
    # detect 함수는 4가지의 매개변수를 갖는다.
    # 첫 번째 인자 : 이미지파일
    # 두 번째 인자 : face_id의 반환 여부
    # 세 번째 인자 : landmarks(눈,코,입 등의 위치)의 반환 여부
    # 네 번째 인자 : 반환할 속성(연령,성별 등)
    emotion = []
    for face in faces:
        emotion.append(face['faceAttributes']) # 터미널 창에 속성값들을 출력

    img = Image.open(img_url) # img 변수에 이미지 파일을 넣어준다.
    draw = ImageDraw.Draw(img)
    for face in faces:
        draw.rectangle(getRectangle(face), outline='red', width=2) # 인식된 얼굴들에 네모 박스 쳐주기
    
    filename1 = 'media/%s_face_%s_%s_%s.png' % (user, year, month, day)
    img.save(filename1)

    return emotion

moodtracker/templates/moodtracker/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}Be.com - 감정일기{% endblock %}</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js"></script>
    {% block extra-style %}{% endblock %}
</head>



<body style="padding-top:90px;">
    <nav class="navbar navbar-expand-lg fixed-top" style="background-color: white;">
        <a class="navbar-brand mx-5 mb-0" href="{% url 'main' %}"><img src="{% static 'img/becom_logo.png' %}" width="140"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item mx-1 btn">
                    <a class="nav-link becom-nav" href="{% url 'main' %}">홈</a></li>
                <li class="nav-item mx-1 btn">
                    <a class="nav-link becom-nav" href="{% url 'myprofile:home' %}">프로필</a></li>
                <li class="nav-item mx-1 btn">
                    <a class="nav-link becom-nav nav-link-active" href="{% url 'moodtracker:home' %}">감정 일기</a></li>
                <li class="nav-item mx-1 btn">
                    <a class="nav-link becom-nav" href="{% url 'mate:home' %}">짝꿍</a></li>
                <li class="nav-item mx-1 btn">
                    <a class="nav-link becom-nav" href="{% url 'forum:home' %}">게시판</a></li>

                
            </ul>

           
            <ul class="navbar-nav">
                <li class="nav-item" style="border: 2px solid #F99B0D;box-sizing:border-box;border-radius:10px;padding:12px 26px;">
                    <a class="register-therapy" href="{% url 'therapy:therapy' %}" style="text-decoration:none;color:#f99b0d;font-family: Noto Sans KR;font-weight: 500;font-size: 16px;">상담 신청하기</a>
                </li>
            </ul>

            <ul class="navbar-nav ml-5 mr-5">
                <li class="nav-item dropdown mx-1 btn " style="background-color: #ffffff;">
                    {% if user.is_active %}
                    <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" style="font-family: Noto Sans KR;font-size: 16px;color: #000000;">
                        <i class="fas fa-user"></i>&ensp;{% firstof user.get_short_name user.get_username %}님 환영합니다!&ensp;</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'logout' %}">로그아웃</a>
                        <a class="dropdown-item" href="{% url 'password_change' %}">비밀번호 변경</a>
                    </div>
                    {% else %}
                    <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">
                        <i class="fas fa-user"></i>&ensp;로그인 하세요&ensp;</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'login' %}">로그인</a>
                        <a class="dropdown-item" href="{% url 'register' %}">회원가입</a>
                    </div>
                    {% endif %}
                </li>
            </ul>

        </div>
    </nav>

    <div class="container">
        {% block content %}{% endblock %}
    </div>


    {% block footer %}{% endblock %}


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="https://kit.fontawesome.com/c998a172fe.js"></script>

    {% block extra-script %}{% endblock %}

</body>
</html>

moodtracker/templates/moodtracker/moodtracker_record.html
{% extends 'moodtracker/base.html' %}
{% block title %}Be.com - 감정일기{% endblock %}
{% load static %}
{% block extra-style %}<link rel="stylesheet" type="text/css" href="{% static 'css/moodtracker_style.css' %}">{% endblock %}
{% block script %}
<script language="javascript">
    
</script>
{% endblock %}

{% block content %}
<div class="moodtracker-nav">
    <ul class="nav">
        <li class="nav-item">
            <a class="nav-link link-active" href="#">쓰기</a>
        </li>
        <li class="nav-item">
            <a class="nav-link link-disabled" href="{% url 'moodtracker:analysis' %}">분석</a>
        </li>
    </ul>
</div>
<div class="main_wrap">
    <div class="calendar">
        <div class="moodtracker-title">감정 일기 리스트</div>
        <div class="calendar-content">
            {% for record in records.all %}
                <a class="record-list" href="{% url 'moodtracker:view' record.id %}">{{ record.pub_date_month }}월 {{ record.pub_date_day }}일의 감정일기</a> <br>
            {% endfor %}
        </div>
        <div class="write-link-div"><a href="{% url 'moodtracker:write' %}" class="write-link">쓰기</a></div>
    </div>
    <div class="record">
        <div class="moodtracker-title">그날의 감정 일기</div>
        <div class="record-content" style="float:left;">
            <div class="record-date">
                <div class="view-record-date">
                    {{sp_record.pub_date_year}}년 {{sp_record.pub_date_month}}월 {{sp_record.pub_date_day}}일
                </div>
                <div class="view-record-mood">
                    {% if sp_record.mood == 'happy' %} <!--저장된 mood에 따라 image src url로 삽입하기-->
                        <img src="{% static 'img/happy_emoji.png' %}" height=50>
                    {% elif sp_record.mood == 'sad' %}
                        <img src="{% static 'img/sad_emoji.png' %}" height=50>
                    {% elif sp_record.mood == 'calm' %}
                        <img src="{% static 'img/calm_emoji.png' %}" height=50>
                    {% elif sp_record.mood == 'angry' %}
                        <img src="{% static 'img/angry_emoji.png' %}" height=50>
                    {% elif sp_record.mood == 'soso' %}
                        <img src="{% static 'img/soso_emoji.png' %}" height=50>
                    {% endif %}
                </div>
            </div>
            <div class="view-record-content">
                {{sp_record.content}}<!--저장된 일기 content 표기-->
            </div>
        </div>
        <div style="float:left;">
            {% if sp_record.images %}
            <div style="width:200px; max-height:250px;">
                <img src="{{ sp_record.images.url }}" style="width:100%; vertical-align:middle; border-radius:10px; padding-bottom: 10px;">
            </div>
            <div style="background-color:#FEF3E1; padding:10px; overflow:auto;">
                <div style="float:left; margin-left:30px; margin-right:20px;">
                    분노<br>
                    경멸<br>
                    혐오<br>
                    공포<br>
                    기쁨<br>
                    중립<br>
                    슬픔<br>
                    놀람<br>
                </div>
                <div style="float:left; text-align:right;">
                    {{sp_record.anger}} %<br>
                    {{sp_record.contempt}} %<br>
                    {{sp_record.disgust}} %<br>
                    {{sp_record.fear}} %<br>
                    {{sp_record.happiness}} %<br>
                    {{sp_record.neutral}} %<br>
                    {{sp_record.sadness}} %<br>
                    {{sp_record.surprise}} %
                </div>
            </div>
            {% else %}
            <div style="padding: 104px 20px; color:#807C77;">
                등록된 사진이 없습니다.
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}