blog/urls.py
from django.urls import path, re_path
from blog import views


app_name = 'blog'
urlpatterns = [

    # Example: /blog/
    path('', views.PostLV.as_view(), name='index'),

    # Example: /blog/post/ (same as /blog/)
    path('post/', views.PostLV.as_view(), name='post_list'),

    # Example: /blog/post/django-example/
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),

    # Example: /blog/archive/
    path('archive/', views.PostAV.as_view(), name='post_archive'),

    # Example: /blog/archive/2019/
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),

    # Example: /blog/archive/2019/nov/
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),

    # Example: /blog/archive/2019/nov/10/
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),

    # Example: /blog/archive/today/
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),

    # Example: /blog/tag/
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),

    # Example: /blog/tag/tagname/
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),

    # Example: /blog/search/
    path('search/', views.SearchFormView.as_view(), name='search'),

    # Example: /blog/add/
    path('add/',
         views.PostCreateView.as_view(), name="add",
    ),

    # Example: /blog/change/
    path('change/',
         views.PostChangeLV.as_view(), name="change",
    ),

    # Example: /blog/99/update/
    path('<int:pk>/update/',
         views.PostUpdateView.as_view(), name="update",
    ),

    # Example: /blog/99/delete/
    path('<int:pk>/delete/',
         views.PostDeleteView.as_view(), name="delete",
    ),
]

forum/urls.py
from django.urls import path
from . import views
import forum.views

app_name='forum'
urlpatterns = [
    path('', views.forum_home, name='home'),
    path('new/', views.new, name='new'),
    path('detail/<int:forum_id>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('postcreate/', views.postcreate, name='postcreate'),
    path('update/<int:forum_id>/', views.update, name='update'),
    path('delete/<int:forum_id>/', views.delete, name='delete'),
    path('search', views.search, name='search'),
]

mate/urls.py
from django.urls import path

from mate import views

app_name = 'mate' 
urlpatterns = [
    path('', views.mate_home, name="home"),
    path('gallery', views.gallery, name="gallery"),
    path('quest', views.quest, name="quest"),
    path('questdone/<int:quest_id>', views.quest_done, name="quest-done"),
    path('upload/', views.upload, name='upload'),
	path('message/', views.send_message, name='send_message'),
]

moodtracker/urls.py
from django.urls import path

from moodtracker import views

app_name = 'moodtracker'
urlpatterns = [    
	path('', views.write_record, name='home'),
	path('record/<int:record_id>', views.view_record, name='view'), 
	path('write/', views.write_record, name='write'),
    path('create/',views.create_record, name='create'),
    path('analysis/', views.analysis, name='analysis'),
]

myprofile/urls.py
from django.urls import path

from myprofile import views

app_name = 'myprofile'
urlpatterns = [
    path('', views.profile_home, name='home'),
    path('detail/<int:profile_id>', views.profile_detail, name='detail'),
    path('upload/', views.upload, name='upload'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

import myprofile.views
import forum.views
import moodtracker.views
import mate.views
import therapy.views

from mysite import views
from mysite.views import HomeView, UserCreateView, UserCreateDoneTV


urlpatterns = [
    path('admin/', admin.site.urls),
    # shkim
    path('accounts/', include('django.contrib.auth.urls')), 
    path('accounts/register/', UserCreateView.as_view(), name='register'), 
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),

    path('', views.main, name='main'),
    path('student_analysis/<int:person_id>', views.student_analysis, name='student_analysis'),
    
    path('blog/', include('blog.urls')),
    path('forum/',include('forum.urls')),
    path('myprofile/',include('myprofile.urls'), name='myprofile'),
    path('moodtracker/', include('moodtracker.urls'), name='moodtracker'),
    path('mate/',include('mate.urls'), name='mate'),
    path('therapy/', include('therapy.urls'), name='therapy'),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

therapy/urls.py
from django.urls import path
from therapy import views

app_name = 'therapy'
urlpatterns = [
    path('', views.therapy, name='therapy'),
    path('result/', views.result, name='result'),
]

mate/models.py
from django.db import models
from django.db.models import IntegerField
from django.contrib.postgres.fields import ArrayField
#from django.contrib.auth.models import User
from myprofile.models import MyProfile
from django.utils import timezone
from datetime import datetime, timedelta

# Create your models here.


class Mate(models.Model):
    mate1 = models.ForeignKey(MyProfile, on_delete=models.CASCADE, verbose_name='USERNAME', blank=True, null=True, related_name='mate1') # 학생1의 id (User 모델과 연결)
    mate2 = models.ForeignKey(MyProfile, on_delete=models.CASCADE, verbose_name='USERNAME', blank=True, null=True, related_name='mate2') # 학생2의 id (User 모델과 연결)
    intimacy = models.IntegerField(default=0) # Quest 3%, Photo 1%, Message 1% 증가
    
    def __str__(self):
        return "%s - %s" % (self.mate1, self.mate2)

class MatePhoto(models.Model):
    mate = models.ForeignKey(Mate, on_delete=models.CASCADE, null=True)
    image = models.ImageField(upload_to='', blank=True, null=True)

    def __str__(self):
        return "%s" % self.mate

class MateQuest(models.Model): # 0이 완료 안 된 상태
    mate = models.ForeignKey(Mate, on_delete=models.CASCADE, null=True) # Mate 모델과 연결
    quest1 = models.IntegerField(default=0)
    quest2 = models.IntegerField(default=0)
    quest3 = models.IntegerField(default=0)
    quest4 = models.IntegerField(default=0)
    quest5 = models.IntegerField(default=0)
    quest6 = models.IntegerField(default=0)
    quest7 = models.IntegerField(default=0)
    quest8 = models.IntegerField(default=0)
    quest9 = models.IntegerField(default=0)
    quest10 = models.IntegerField(default=0)
    quest11 = models.IntegerField(default=0)
    quest12 = models.IntegerField(default=0)

    def __str__(self):
        return "%s" % self.mate

class MateMsg(models.Model):
    mate = models.ForeignKey(Mate, on_delete=models.CASCADE, null=True) # Mate 모델과 연결
    sender = models.ForeignKey(MyProfile, on_delete=models.CASCADE, verbose_name='USERNAME', blank=True, null=True)
    content = models.CharField(max_length=400)
    created_date = models.DateTimeField(auto_now_add=True, verbose_name='작성일')

    @property
    def created_string(self): # time 변수에 현재시간에서 작성시간을 뺀 작성경과 시간을 저장
        time = datetime.now(tz=timezone.utc) - self.created_date

        if time < timedelta(minutes=1): # timedelta 메소드를 사용하여 분, 시간, 일 단위로 표시
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(int(time.seconds / 60)) + '분 전'
        elif time < timedelta(days=1):
            return str(int(time.seconds / 3600)) + '시간 전'
        elif time < timedelta(days=7):
            time = datetime.now(tz=timezone.utc).date() - self.created_date.date()
            return str(time.days) + '일 전'
        else:
            return False # 7일이 지날 경우 false를 반환하여 템플릿에서 원래의 Date형식으로 표시

#class Task(models.Model):
#    mate = models.ForeignKey(Mate, on_delete=models.CASCADE, null=True) # Mate 모델과 연결
#    task = ArrayField(IntegerField(), size=8)

mate/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.db.models import Q # OR문 추가
from django.utils import timezone
from datetime import datetime

from .models import Mate, MatePhoto, MateQuest, MateMsg
from myprofile.models import MyProfile
from django.contrib.auth.models import User

from django.contrib.auth.decorators import login_required

@login_required
def mate_home(request):
    user = request.user
    profile = MyProfile.objects.get(username=user)
    mate = Mate.objects.get(Q(mate1=profile) | Q(mate2=profile))
    photos = MatePhoto.objects.filter(mate=mate)
    quests = MateQuest.objects.get(mate=mate)
    quest_done_num = quest_percent(quests)
    quest_done_per = round(quest_done_num/12*100)
    messages = MateMsg.objects.filter(mate=mate)

    item={
        'mate' : mate,
        'profile' : profile,
        'photos' : photos,
        'quests' : quests,
        'quest_done_per' : quest_done_per,
        'messages' : messages,
    }
    return render(request, 'mate/mate.html', item)

def send_message(request):
    user = request.user
    profile = MyProfile.objects.get(username=user)
    mate = Mate.objects.get(Q(mate1=profile) | Q(mate2=profile))
    
    message = MateMsg()
    message.mate = mate
    message.sender = profile
    message.content = request.GET['message']
    message.created_date = timezone.now()
    message.save()

    if mate.intimacy < 100:
        mate.intimacy += 1 # 친밀도 1% 증가
        mate.save()

    return redirect('/mate')

@login_required
def gallery(request):
    user = request.user
    profile = MyProfile.objects.get(username=user)
    mate = Mate.objects.get(Q(mate1=profile) | Q(mate2=profile))
    photos = MatePhoto.objects.filter(mate=mate)
    return render(request, 'mate/gallery.html', {'photos':photos})

def upload(request): 
    if(request.method == 'POST'):
        user = request.user
        profile = MyProfile.objects.get(username=user)
        mate = Mate.objects.get(Q(mate1=profile) | Q(mate2=profile))
        # name 속성이 imgs인 input 태그로부터 받은 파일들을 반복문을 통해 하나씩 가져온다 
        for img in request.FILES.getlist('imgs'):
            photo = MatePhoto() # ProfilePhoto 객체를 하나 생성한다.
            photo.mate = mate # 외래키로 현재 생성한 MyProfile의 기본키를 참조한다.
            photo.image = img # imgs로부터 가져온 이미지 파일 하나를 저장한다.
            photo.save() # 데이터베이스에 저장
        if mate.intimacy < 100:
            mate.intimacy += 1 # 친밀도 1% 증가
            mate.save()
        return redirect('/mate/gallery')
    else:
        return render(request, 'mate/mate.html')

@login_required
def quest(request):
    user = request.user
    profile = MyProfile.objects.get(username=user)
    mate = Mate.objects.get(Q(mate1=profile) | Q(mate2=profile))
    quests = MateQuest.objects.get(mate=mate)
    quest_done_num = quest_percent(quests)
    quest_done_per = round(quest_done_num/12*100)

    item={
        'quests': quests,
        'quest_done_num' : quest_done_num,
        'quest_done_per' : quest_done_per,
    }
    #new = Task()
    #new.mate = mate
    #new.task = [0, 0, 0, 0, 0, 0, 0, 0]
    #new.save()
    return render(request, 'mate/quest.html', item)

def quest_done(request, quest_id):
    user = request.user
    profile = MyProfile.objects.get(username=user)
    mate = Mate.objects.get(Q(mate1=profile) | Q(mate2=profile))
    quests = MateQuest.objects.get(mate=mate)
    find_quest(quest_id, quests)
    if mate.intimacy < 100:
        mate.intimacy += 3 # 친밀도 3% 증가
        mate.save()
    return redirect('/mate/quest')

# Quest_id 찾아서 완료 처리
def find_quest(quest_id, quests):
    if quest_id==1:
        quests.quest1 = 1
    elif quest_id==2:
        quests.quest2 = 1
    elif quest_id==3:
        quests.quest3 = 1
    elif quest_id==4:
        quests.quest4 = 1
    elif quest_id==5:
        quests.quest5 = 1
    elif quest_id==6:
        quests.quest6 = 1
    elif quest_id==7:
        quests.quest7 = 1
    elif quest_id==8:
        quests.quest8 = 1
    elif quest_id==9:
        quests.quest9 = 1
    elif quest_id==10:
        quests.quest10 = 1
    elif quest_id==11:
        quests.quest11 = 1
    elif quest_id==12:
        quests.quest12 = 1
    
    quests.save()

# 완료된 Quest 수 계산
def quest_percent(quests):
    quest_done_num = 0
    if quests.quest1==1:
        quest_done_num += 1
    if quests.quest2==1:
        quest_done_num += 1
    if quests.quest3==1:
        quest_done_num += 1
    if quests.quest4==1:
        quest_done_num += 1
    if quests.quest5==1:
        quest_done_num += 1
    if quests.quest6==1:
        quest_done_num += 1
    if quests.quest7==1:
        quest_done_num += 1
    if quests.quest8==1:
        quest_done_num += 1
    if quests.quest9==1:
        quest_done_num += 1
    if quests.quest10==1:
        quest_done_num += 1
    if quests.quest11==1:
        quest_done_num += 1
    if quests.quest12==1:
        quest_done_num += 1
    
    return quest_done_num

mate/templates/mate/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}Be.com - 짝꿍{% endblock %}</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js"></script>
    {% block extra-style %}{% endblock %}
</head>



<body style="padding-top:90px;">
    <nav class="navbar navbar-expand-lg fixed-top" style="background-color: white;">
        <a class="navbar-brand mx-5 mb-0" href="{% url 'main' %}"><img src="{% static 'img/becom_logo.png' %}" width="140"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item mx-1 btn">
                    <a class="nav-link becom-nav" href="{% url 'main' %}">홈</a></li>
                <li class="nav-item mx-1 btn">
                    <a class="nav-link becom-nav" href="{% url 'myprofile:home' %}">프로필</a></li>
                <li class="nav-item mx-1 btn">
                    <a class="nav-link becom-nav" href="{% url 'moodtracker:home' %}">감정 일기</a></li>
                <li class="nav-item mx-1 btn">
                    <a class="nav-link becom-nav link-active" href="{% url 'mate:home' %}">짝꿍</a></li>
                <li class="nav-item mx-1 btn">
                    <a class="nav-link becom-nav" href="{% url 'forum:home' %}">게시판</a></li>

                
            </ul>

           
            <ul class="navbar-nav">
                <li class="nav-item" style="border: 2px solid #F99B0D;box-sizing:border-box;border-radius:10px;padding:12px 26px;">
                    <a class="register-therapy" href="{% url 'therapy:therapy' %}" style="text-decoration:none;color:#f99b0d;font-family: Noto Sans KR;font-weight: 500;font-size: 16px;">상담 신청하기</a>
                </li>
            </ul>

            <ul class="navbar-nav ml-5 mr-5">
                <li class="nav-item dropdown mx-1 btn " style="background-color: #ffffff;">
                    {% if user.is_active %}
                    <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" style="font-family: Noto Sans KR;font-size: 16px;color: #000000;">
                        <i class="fas fa-user"></i>&ensp;{% firstof user.get_short_name user.get_username %}님 환영합니다!&ensp;</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'logout' %}">로그아웃</a>
                        <a class="dropdown-item" href="{% url 'password_change' %}">비밀번호 변경</a>
                    </div>
                    {% else %}
                    <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">
                        <i class="fas fa-user"></i>&ensp;로그인 하세요&ensp;</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'login' %}">로그인</a>
                        <a class="dropdown-item" href="{% url 'register' %}">회원가입</a>
                    </div>
                    {% endif %}
                </li>
            </ul>

        </div>
    </nav>

    <div class="container">
        {% block content %}{% endblock %}
    </div>


    {% block footer %}{% endblock %}


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="https://kit.fontawesome.com/c998a172fe.js"></script>

    {% block extra-script %}{% endblock %}

</body>
</html>

mate/templates/mate/gallery.html
{% extends 'mate/base.html' %}

{% load static %}

{% block extra-style %}<link rel="stylesheet" type="text/css" href="{% static 'css/mate_style.css' %}">{% endblock %}

{% block title %}Be.com - 짝꿍{% endblock %}


{% block content %}
<div class="container">
    <div class="go-home-button"><a href="{% url 'mate:home' %}" style="color:#5B5652;"><img src="{% static 'img/left_arrow.png' %}" height="16" style="float:left; margin-top:4px;">짝꿍 홈</a></div>
    <div class="mate-detail">
        <div class="mate-detail-title">갤러리</div>
        <div style="float:right;">
            <form  method="POST" action="{% url 'mate:upload' %}" enctype="multipart/form-data">
                {% csrf_token %}
                <!--
                <select name="topic">
                    <option value="profile-image">프로필 사진</option>
                    <option value="favorite-spot">좋아하는 장소</option>
                    <option value="happiness">행복할 때</option>
                    <option value="friends">친구들과 함께</option>
                    <option value="favorite-movie">좋아하는 영화</option>
                    <option value="else">기타</option>
                </select>
                -->
                <div class="filebox">
                    <input type="file" name="imgs" multiple>
                    <input type="submit" value="업로드" style="background:#f99b0d; color:white; border:none; border-radius:5px; padding:5px 12px;">
                </div>
            </form>
        </div>
        <div class="mate-gallery-imgs" style="width:1000px; height:550px; overflow:auto;">
            {% for photo in photos.all %}
                <img src="{{photo.image.url}}" height="250" class="mate-gallery-img">
            {% endfor %}
        </div>

    </div>
</div>
{% endblock content %}

mate/templates/mate/mate.html
{% extends 'mate/base.html' %}

{% load static %}

{% block extra-style %}<link rel="stylesheet" type="text/css" href="{% static 'css/mate_style.css' %}">{% endblock %}

{% block title %}Be.com - 짝꿍{% endblock %}


{% block content %}
<div class="container">
  <div class="col-md-5" style="float: left;">
    <!-- 프로필사진 -->
    <div class="row mb-2">
      <div class="mate-home-profile row no-gutters overflow-hidden flex-md-row mb-4 h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <div class="mate-title">프로필</div>
          <div class="mate-profile-img">
            <div class="mate-profile">
              <a href="{% url 'myprofile:detail' mate.mate1.id %}">
                <img src="{{mate.mate1.profile_image.url}}" width="100" height="100" style="border-radius:50px; border: 0.75px solid #C4C4C4;">
                <div style="width:100px;">{{mate.mate1.username}}</div>
              </a>
            </div>
            <img src="{% static 'img/mate-zigzag.png' %}" height="50" style="float:left; margin-top:20px;">
            <div class="mate-profile">
              <a href="{% url 'myprofile:detail' mate.mate2.id %}">
                <img src="{{mate.mate2.profile_image.url}}" width="100" height="100" style="border-radius:50px; border: 0.75px solid #C4C4C4;">
                <div style="width:100px;">{{mate.mate2.username}}</div>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
    
    <!-- Mate-Message -->
    <div class="row mb-2">
      <div class="mate-home-message row no-gutters overflow-hidden flex-md-row mb-4 h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <div class="mate-title">쪽지</div>
          <div class="message">
            <div class="message-list">
              {% for message in messages.all %}
                {% if message.sender == profile %}
                  <div class="msg-mine">
                    <div class="msg-mine-content">{{message.content}}</div>
                    <div class="msg-mine-date">
                      {% if message.created_string == False %}
                        <div>{{ message.created_date|date:'m월 d일' }}</div>
                      {% else %}
                        <div>{{ message.created_string }}</div>
                      {% endif %}
                    </div>
                  </div>
                {% else %}
                  <div class="msg-mate">
                    <div class="msg-mate-content">{{message.content}}</div>
                    <div class="msg-mate-date">
                      {% if message.created_string == False %}
                        {{ message.created_date|date:'m월 d일' }}
                      {% else %}
                        {{ message.created_string }}
                      {% endif %}
                    </div>
                  </div>
                {% endif %}
              {% endfor %}
            </div>            
            <div class="message-input" style="width:100%; padding-top:12px;">
              <form action="{% url 'mate:send_message' %}">
                <input type="text" name="message" size="35" style="height:50px; border: 1px solid #BDBDBD; box-sizing: border-box; border-radius: 100px;">
                <input type="image" src="{% static 'img/send_button.png' %}" name="submit" width="40" height="40" class="message-send-button">
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-7" style="float: right;">
    <!-- 게이지 -->
    <div class="row mb-2">
      <div class="mate-home-percent row no-gutters overflow-hidden flex-md-row mb-4 h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <div class="mate-title">친밀도</div>
          <div class="intimacy">
            <div class="intimacy-text">
              {% if mate.intimacy >= 0 and mate.intimacy <= 20 %}
              아직은 어색하지만 서로에게 먼저 다가가보세요.<br>의외의 공통점을 발견할 수 있을지도 몰라요!
              {% elif mate.intimacy <= 40 %}
              한 발짝 한 발짝 서로에게 다가가고 있는 중인가요?<br>퀘스트를 완료하다보면 더욱 가까워질 수 있을 거예요!
              {% elif mate.intimacy <= 60 %}
              벌써 함께 보낸 시간이 이만큼이나 되네요!<br>앞으로 좋은 추억을 더 쌓아가길 바라요.
              {% elif mate.intimacy <= 80 %}
              두 분 정말 잘 맞는 친구네요!<br>절친이 되기까지 얼마 안 남았어요!
              {% elif mate.intimacy <= 100 %}
              한 학기 동안 정말 많은 시간을 함께했네요.<br>이제 두 분이 서로를 잘 아는 친구가 되었길 바라요!
              {% endif %}
            </div>
            <div class="progress">
              <div class="progress-bar" role="progressbar" aria-valuemin="0" aria-valuemax="100" style="width:{{mate.intimacy}}%">
                {{mate.intimacy}}%
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Mate-Photo -->
    <div class="row mb-2">
      <div class="mate-home-gallery row no-gutters overflow-hidden flex-md-row mb-4 h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <div>
            <div class="mate-title">갤러리</div>
            <a href="{% url 'mate:gallery' %}" style="font-weight:bold; float:right; color:#7A7A7A; font-size:14px;">더보기</a>
          </div>
          <div class="mate-gallery-imgs">
            {% for photo in photos.all|slice:":3" %} <!-- 3개의 사진만 보여준다. -->
                <img src="{{photo.image.url}}" height="150" class="mate-gallery-img">
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
    <!-- Mate-Quest -->
    <div class="row mb-2">
      <div class="mate-home-quest row no-gutters overflow-hidden flex-md-row mb-4 h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <div>
            <div class="mate-title">퀘스트</div>
            <a href="{% url 'mate:quest' %}" style="font-weight:bold; float:right; color:#7A7A7A; font-size:14px;">더보기</a>
          </div>
          <!--<div class="mate-quest-percent">
            <div class="progress">
                <div class="progress-bar" role="progressbar" aria-valuemin="0" aria-valuemax="100" style="width:{{quest_done_per}}%">
                  {{quest_done_per}}%
                </div>
              </div>
          </div>-->
          <div class="home-mate-quest-list">
            {% if quests.quest1 == 0 %}
              <div class="home-mate-quest-card" style="border: 1px solid #00D2C9; color: #00D2C9; border: 1px solid #00D2C9;">도서관 가기</div>
            {% endif %}
            {% if quests.quest2 == 0 %}
              <div class="home-mate-quest-card" style="border: 1px solid #f99b0d; color: #f99b0d; border: 2px solid #f99b0d;">산책하기</div>
            {% endif %}
            {% if quests.quest3 == 0 %}
              <div class="home-mate-quest-card" style="border: 1px solid #D391FF; color: #D391FF; border: 2px solid #D391FF;">숙제하기</div>
            {% endif %}
            {% if quests.quest4 == 0 %}
              <div class="home-mate-quest-card" style="border: 1px solid #0D6BF9; color: #0D6BF9; border: 2px solid #0D6BF9;">선물 주기</div>
            {% endif %}
            {% if quests.quest5 == 0 %}
              <div class="home-mate-quest-card" style="border: 1px solid #FF7B55; color: #FF7B55; border: 2px solid #FF7B55;">봉사활동 가기</div>
            {% endif %}
            {% if quests.quest6 == 0 %}
              <div class="home-mate-quest-card" style="border: 1px solid #00D2C9; color: #00D2C9; border: 2px solid #00D2C9;">카페 가기</div>
            {% endif %}
            {% if quests.quest7 == 0 %}
              <div class="home-mate-quest-card" style="border: 1px solid #f99b0d; color: #f99b0d; border: 2px solid #f99b0d;">자전거 타기</div>
            {% endif %}
            {% if quests.quest8 == 0 %}
              <div class="home-mate-quest-card" style="border: 1px solid #D391FF; color: #D391FF; border: 2px solid #D391FF;">쇼핑하기</div>
            {% endif %}
            {% if quests.quest9 == 0 %}
              <div class="home-mate-quest-card" style="border: 1px solid #0D6BF9; color: #0D6BF9; border: 2px solid #0D6BF9;">편지 쓰기</div>
            {% endif %}
            {% if quests.quest10 == 0 %}
              <div class="home-mate-quest-card" style="border: 1px solid #FF7B55; color: #FF7B55; border: 2px solid #FF7B55;">밥 먹기</div>
            {% endif %}
            {% if quests.quest11 == 0 %}
              <div class="home-mate-quest-card" style="border: 1px solid #BBB500; color: #BBB500; border: 2px solid #BBB500;">영화 보기</div>
            {% endif %}
            {% if quests.quest12 == 0 %}
              <div class="home-mate-quest-card" style="border: 1px solid #F90D6B; color: #F90D6B; border: 2px solid #F90D6B;">게임하기</div>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}