blog/urls.py
from django.urls import path, re_path
from blog import views


app_name = 'blog'
urlpatterns = [

    # Example: /blog/
    path('', views.PostLV.as_view(), name='index'),

    # Example: /blog/post/ (same as /blog/)
    path('post/', views.PostLV.as_view(), name='post_list'),

    # Example: /blog/post/django-example/
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),

    # Example: /blog/archive/
    path('archive/', views.PostAV.as_view(), name='post_archive'),

    # Example: /blog/archive/2019/
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),

    # Example: /blog/archive/2019/nov/
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),

    # Example: /blog/archive/2019/nov/10/
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),

    # Example: /blog/archive/today/
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),

    # Example: /blog/tag/
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),

    # Example: /blog/tag/tagname/
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),

    # Example: /blog/search/
    path('search/', views.SearchFormView.as_view(), name='search'),

    # Example: /blog/add/
    path('add/',
         views.PostCreateView.as_view(), name="add",
    ),

    # Example: /blog/change/
    path('change/',
         views.PostChangeLV.as_view(), name="change",
    ),

    # Example: /blog/99/update/
    path('<int:pk>/update/',
         views.PostUpdateView.as_view(), name="update",
    ),

    # Example: /blog/99/delete/
    path('<int:pk>/delete/',
         views.PostDeleteView.as_view(), name="delete",
    ),
]

forum/urls.py
from django.urls import path
from . import views
import forum.views

app_name='forum'
urlpatterns = [
    path('', views.forum_home, name='home'),
    path('new/', views.new, name='new'),
    path('detail/<int:forum_id>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('postcreate/', views.postcreate, name='postcreate'),
    path('update/<int:forum_id>/', views.update, name='update'),
    path('delete/<int:forum_id>/', views.delete, name='delete'),
    path('search', views.search, name='search'),
]

mate/urls.py
from django.urls import path

from mate import views

app_name = 'mate' 
urlpatterns = [
    path('', views.mate_home, name="home"),
    path('gallery', views.gallery, name="gallery"),
    path('quest', views.quest, name="quest"),
    path('questdone/<int:quest_id>', views.quest_done, name="quest-done"),
    path('upload/', views.upload, name='upload'),
	path('message/', views.send_message, name='send_message'),
]

moodtracker/urls.py
from django.urls import path

from moodtracker import views

app_name = 'moodtracker'
urlpatterns = [    
	path('', views.write_record, name='home'),
	path('record/<int:record_id>', views.view_record, name='view'), 
	path('write/', views.write_record, name='write'),
    path('create/',views.create_record, name='create'),
    path('analysis/', views.analysis, name='analysis'),
]

myprofile/urls.py
from django.urls import path

from myprofile import views

app_name = 'myprofile'
urlpatterns = [
    path('', views.profile_home, name='home'),
    path('detail/<int:profile_id>', views.profile_detail, name='detail'),
    path('upload/', views.upload, name='upload'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

import myprofile.views
import forum.views
import moodtracker.views
import mate.views
import therapy.views

from mysite import views
from mysite.views import HomeView, UserCreateView, UserCreateDoneTV


urlpatterns = [
    path('admin/', admin.site.urls),
    # shkim
    path('accounts/', include('django.contrib.auth.urls')), 
    path('accounts/register/', UserCreateView.as_view(), name='register'), 
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),

    path('', views.main, name='main'),
    path('student_analysis/<int:person_id>', views.student_analysis, name='student_analysis'),
    
    path('blog/', include('blog.urls')),
    path('forum/',include('forum.urls')),
    path('myprofile/',include('myprofile.urls'), name='myprofile'),
    path('moodtracker/', include('moodtracker.urls'), name='moodtracker'),
    path('mate/',include('mate.urls'), name='mate'),
    path('therapy/', include('therapy.urls'), name='therapy'),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

therapy/urls.py
from django.urls import path
from therapy import views

app_name = 'therapy'
urlpatterns = [
    path('', views.therapy, name='therapy'),
    path('result/', views.result, name='result'),
]

forum/models.py
from django.db import models
from django.contrib.auth.models import User
from myprofile.models import MyProfile, MyClass

# Create your models here.
class Forum(models.Model):
    title = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    body = models.TextField()
    images = models.ImageField(blank=True, upload_to="images", null=True)
    #추가
    writer = models.ForeignKey(MyProfile, on_delete=models.CASCADE, verbose_name='USERNAME', blank=True, null=True, related_name='writer')
    #ForeignKey(User, verbose_name = "작성자", on_delete = models.CASCADE)


    def __str__(self):
        return self.title

    def summary(self):
        return self.body[:100]

forum/forms.py
from django import forms
from .models import Forum

class ForumUpdate(forms.ModelForm):
    class Meta:
        model = Forum
        fields = ['title','body','writer']#writer 추가

forum/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.core.paginator import Paginator
from django.db.models import Q
from .models import Forum
from .forms import ForumUpdate
from .models import MyProfile,MyClass
from django.contrib.auth.models import User

from django.contrib.auth.decorators import login_required

@login_required
def forum_home(request):
    user = request.user   
    #print(user)  
    forums = Forum.objects.order_by('-id')
    forum_list = Forum.objects.all().order_by('-id')
    paginator = Paginator(forum_list,10)
    page = request.GET.get('page')
    posts = paginator.get_page(page)

    my = MyProfile.objects.get(username=user)
    myclass=MyClass.objects.filter( hak=my.school_year,ban=my.school_class)
    #print(myclass)

    item = {
        'forums':forums,
        'posts':posts,
        'my':my,
        'myclass':myclass
    }
    return render(request,'forum/forumhome.html', item)

@login_required
def detail(request, forum_id):
    user = request.user # 현재 로그인한 사용자
    forum_detail = get_object_or_404(Forum, pk=forum_id)
    person = MyProfile.objects.get(pk=forum_detail.writer.id) # 보여줄 글의 주인

    if person.username==user : # 내가 쓴 글일 때
        detail = 'my'
    else: # 다른 친구가 쓴 글일 때
        detail = 'friend'

    

    item={
        'detail' : detail,
        'forum' : forum_detail,
    }
    return render(request, 'forum/detail.html', item)

@login_required
def create(request):
    return render(request, 'forum/create.html')

@login_required
def postcreate(request):
    user = request.user    
    my = MyProfile.objects.get(username=user)
    forum = Forum()
    forum.title = request.POST['title']
    forum.body = request.POST['body']
    forum.images = request.FILES['images']
    forum.writer = my
    forum.pub_date = timezone.datetime.now()
    #추가
    myclass=MyClass.objects.get(hak=my.school_year,ban=my.school_class)
    if myclass.class_intimacy < 100:
        myclass.class_intimacy += 1 # 친밀도 1% 증가
        myclass.save()

    forum.save()

    return redirect('/forum/detail/' + str(forum.id))

@login_required
def update(request, forum_id):
    forum = Forum.objects.get(id=forum_id)

    if request.method =='POST':
        form = ForumUpdate(request.POST)
        if form.is_valid():
            forum.title = form.cleaned_data['title']
            forum.body = form.cleaned_data['body']
            forum.pub_date=timezone.now()
            forum.save()
            return redirect('/forum/detail/' + str(forum.id))
    else:
        form = ForumUpdate(instance = forum)
 
        return render(request,'forum/update.html', {'form':form})

@login_required
def delete(request, forum_id):
    forum = Forum.objects.get(id=forum_id)
    forum.delete()
    return redirect('/')

@login_required
def new(request):
    full_text = request.GET['fulltext']

    word_list = full_text.split()

    word_dictionary = {}

    for word in word_list:
        if word in word_dictionary:
            # Increase
            word_dictionary[word] += 1
        else:
            # add to the dictionary
            word_dictionary[word] = 1

    return render(request, 'forum/new.html', {'fulltext': full_text, 'total': len(word_list), 'dictionary': word_dictionary.items()} )

@login_required
def search(request):
    forums = Forum.objects.all().order_by('-id')

    q = request.POST.get('q', "") 

    if q:
        forums = forums.filter(title__icontains=q)
        return render(request, 'forum/search.html', {'forums' : forums, 'q' : q})
    
    else:
        return render(request, 'forum/search.html')

forum/templates/forum/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}Be.com - 게시판{% endblock %}</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js"></script>
    {% block extra-style %}{% endblock %}
</head>



<body style="padding-top:90px;">
    <nav class="navbar navbar-expand-lg fixed-top" style="background-color: white;">
        <a class="navbar-brand mx-5 mb-0" href="{% url 'main' %}"><img src="{% static 'becom_logo.png' %}" width="140"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item mx-1 btn">
                    <a class="nav-link becom-nav" href="{% url 'main' %}">홈</a></li>
                <li class="nav-item mx-1 btn">
                    <a class="nav-link becom-nav" href="{% url 'myprofile:home' %}">프로필</a></li>
                <li class="nav-item mx-1 btn">
                    <a class="nav-link becom-nav" href="{% url 'moodtracker:home' %}">감정 일기</a></li>
                <li class="nav-item mx-1 btn">
                    <a class="nav-link becom-nav" href="{% url 'mate:home' %}">짝꿍</a></li>
                <li class="nav-item mx-1 btn">
                    <a class="nav-link becom-nav link-active" href="{% url 'forum:home' %}">게시판</a></li>

                
            </ul>

           
            <ul class="navbar-nav">
                <li class="nav-item" style="border: 2px solid #F99B0D;box-sizing:border-box;border-radius:10px;padding:12px 26px;">
                    <a class="register-therapy" href="{% url 'therapy:therapy' %}" style="text-decoration:none;color:#f99b0d;font-family: Noto Sans KR;font-weight: 500;font-size: 16px;">상담 신청하기</a>
                </li>
            </ul>

            <ul class="navbar-nav ml-5 mr-5">
                <li class="nav-item dropdown mx-1 btn " style="background-color: #ffffff;">
                    {% if user.is_active %}
                    <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" style="font-family: Noto Sans KR;font-size: 16px;color: #000000;">
                        <i class="fas fa-user"></i>&ensp;{% firstof user.get_short_name user.get_username %}님 환영합니다!&ensp;</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'logout' %}">로그아웃</a>
                        <a class="dropdown-item" href="{% url 'password_change' %}">비밀번호 변경</a>
                    </div>
                    {% else %}
                    <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">
                        <i class="fas fa-user"></i>&ensp;로그인 하세요&ensp;</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'login' %}">로그인</a>
                        <a class="dropdown-item" href="{% url 'register' %}">회원가입</a>
                    </div>
                    {% endif %}
                </li>
            </ul>

        </div>
    </nav>

    <div class="container">
        {% block content %}{% endblock %}
    </div>


    {% block footer %}{% endblock %}


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="https://kit.fontawesome.com/c998a172fe.js"></script>

    {% block extra-script %}{% endblock %}

</body>
</html>

forum/templates/forum/create.html
{% extends 'forum/base.html' %}

{%load static%}

{% block extra-style %}<link rel="stylesheet" type="text/css" href="{% static 'css/forum_style.css' %}">{% endblock %}

{% block content %}

<br>
<div class="container">
	<div class="forum-title">게시글 작성하기</div>
	<form action="{% url 'forum:postcreate' %}" enctype="multipart/form-data" method="POST" style="margin-bottom:48px;">
	  {% csrf_token %}
	  <div class="forum-title">제목: </div>
	  <input type="text" size=125 maxlength=20  name="title">
	  <br>
	  <br>
	  <div class="forum-title">본문: </div>
	  <textarea cols=130 rows=20 name="body"></textarea>
	  <br>
	  <br>
	  <div class="forum-title">사진: </div>
	  <input type="file" name="images" accept="image/*">
	  <br>
	  <br>
	  <input type="submit" value="글쓰기" style="background:#f99b0d; color:white; border:none; border-radius:5px; padding:5px 12px;">
	</form>
</div>

{% endblock %}

forum/templates/forum/detail.html
{% extends 'forum/base.html' %}


{%load static%}

{% block extra-style %}<link rel="stylesheet" type="text/css" href="{% static 'css/forum_style.css' %}">{% endblock %}
{% block content %}
    
  <!--<a href="{% url 'forum:home' %}">
    목록으로 돌아가기
  </a>-->  
    
    <div class="container"> 
      <div class="go-home-button"><a href="{% url 'forum:home' %}" style="color:#5B5652;"><img src="{% static 'left_arrow.png' %}" height="16" style="float:left; margin-top:4px;">목록으로 돌아가기</a></div>

        <div class="card">
          <div class="card-body">
            <div style="display:block;">
              <div style="overflow:auto; padding:12px;">
                <div class="forum-title" style="display:inline-block; float:left; margin-bottom:0;">{{ forum.title }}</div>
                <div style="float:right; font-size:14px;">{{ forum.pub_date }}</div>
              </div>
              <div style="width:100%; height:1px; background-color:#7D7D7D"></div>
              <div style="overflow:auto; padding:12px;">
                <div style="float:right;">
                  <img src="{{forum.writer.profile_image.url}}" width="32" height="32" style="border-radius:16px; border: 0.5px solid #C4C4C4; margin-right:12px;">
                  <span>{{forum.writer}}</span>
                </div>
              </div>
              <div style="width:100%; height:1px; background-color:#7D7D7D"></div>
              <div style="padding:20px 12px;">{{ forum.body }}</div>
            </div>

            <br>
            {% if forum.images %}
                <img src="{{ forum.images.url }}" height="300" style="border-radius:10px;">
            {% endif %}
            <br>
            <br>
            <!--내가 쓴 글에만 수정/삭제 버튼 노출-->
            {% if detail == 'my' %}                
              <a href="{% url 'forum:update' forum.id %}"><img src="/static/update.png" alt="수정" ></a>
              <a href="{% url 'forum:delete' forum.id %}"><img src="/static/delete.png" alt="삭제"></a>
            {% endif %}
          </div>
        </div>

        <div id="disqus_thread"></div>
      </div>
        
{% endblock %}
{% block extra-script %}
<script>
/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION
*  BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT:
*  https://disqus.com/admin/universalcode/#configuration-variables*/

var disqus_config = function () {
    this.page.identifier = '{{ disqus_id }}';
    this.page.url = '{{ disqus_url }}';
    this.page.title = '{{ disqus_title }}';
};

(function() { // DON'T EDIT BELOW THIS LINE
    var d = document, s = d.createElement('script');
    s.src = 'https://be-com.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
{% endblock %}

forum/templates/forum/forumhome.html
{% extends 'forum/base.html' %}

{%load static%}

{% block extra-style %}<link rel="stylesheet" type="text/css" href="{% static 'css/forum_style.css' %}">{% endblock %}


{% block content %}
  <style>
  /* 본문 내 이미지 요소의 'position' 속성을 'relative'로 지정 */
    img.write_b { 
      position: relative;
      left: 1045px;
      top: 3 px;
    }
  
    .write{
     
      padding-top: 10px;
      left: 1040px;
      top: 3px;
    }
  </style>



  <div class="write" style="padding-top:10px">
    <!--<input type="submit" value="글쓰기" style="background:#f99b0d; color:white; border:none; border-radius:5px; padding:5px 12px;">-->
    <a href="{% url 'forum:create' %}" style="background:#f99b0d; color:white; font-weight:bold; float:right;  border:none; border-radius:5px; padding:5px 12px;  font-size:14px;">글쓰기</a>

  </div>

  <!--<a href="{% url 'forum:create' %}">
    <img src="{%static 'button_write.png'%}" class="write_b" height="30" alt="글쓰기 버튼" > 
  </a>-->

  <div class="container">
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th  width="30%">제목</th>
          <th  width="40%">내용</th>
          <th width="15%">날짜</th>
          <th  width="25%">작성자</th>
        </tr>
      </thead>
      <tbody>
        {%for forum in posts%}
        <tr>
          
          <th>{{forum.title}}</th>
          <th><a href="{% url 'forum:detail' forum.id %}">{{ forum.summary }}</a> </th>
          <th>{{ forum.pub_date | date:"Y-m-d" }}</th>
          <th><img src="{{forum.writer.profile_image.url}}" width="32" height="32" style="border-radius:16px; border: 0.5px solid #C4C4C4; margin-right:12px;">{{forum.writer}}</th>
        </tr>
        {% endfor %} 
      </tbody>
    </table>
<!--
    {%if posts.has_previous%}
    <a href="?page=1"><First></a>
    <a href="?page={{posts.previous_page_number}}">Previous</a>
    {%endif%}

    <span>{{posts.number}}</span>
    <span>of</span>
    <span>{{posts.paginator.num_pages}}</span>

    {%if posts.has_next%}
    <a href="?page={{posts.next_page_number}}">Next</a>
    <a href="?page={{posts.paginator.num_pages}}">Last</a>
    {%endif%}-->

    <div class="row mt-2">
      <div class="col-12">
          <nav>
              <ul class="pagination justify-content-center">
                {%if posts.has_previous%}                        
                  <li class="page-item">
                      <a class="page-link" href="?page={{posts.previous_page_number}}">이전으로</a>
                  </li>
                  {% else %}
                  <li class="page-item disabled">
                      <a class="page-link" href="#">이전으로</a>
                  </li>
                  {% endif %}
                  <li class="page-item">
                      <a class="page-link" href="#">{{posts.number}}/{{posts.paginator.num_pages}}</a>
                  </li>
                  {% if products.has_next %}
                  <li class="page-item">
                      <a class="page-link" href="?page={{posts.next_page_number}}">다음으로</a>
                  </li>
                  {% else %}
                  <li class="page-item disabled">
                      <a class="page-link" href="#">다음으로</a>
                  </li>
                  {% endif %}
              </ul>
          </nav>
      </div>
  </div>
  </div>

{% endblock %}

forum/templates/forum/new.html
<h1>new page!</h1>

<a href="{% url 'forum:home' %}">home</a>

<br>
{{fulltext}}
<br>
<br>

{% for word, countTotal in dictionary %}
{{ word }} - {{ countTotal }}
<br>
{% endfor %}

forum/templates/forum/search.html
{% extends 'forum/base.html' %}

{% block content %}

    {% if not forums %}

        <h1>검색 결과가 없습니다</h1>

    {% else %}

        {% for forum in forums.all %}
        <div class="container"> 
            <div class="card">
                <div class="card-body">
                    <h1>{{ forum.title }}</h1>
                    <p>{{ forum.pub_date | date:"Y-m-d" }}</p>
                    <p>{{ forum.summary }}<a href="{% url 'forum:detail' forum.id %}"> ...자세히 보기</a></p> 
                </div>
            </div>
        </div>
        <br>
        {% endfor %}

    {% endif %}

{% endblock %}

forum/templates/forum/update.html
{% extends 'forum/base.html' %}

{% block content %}

<br>
<div class="container">
	<form method="POST">
	  {% csrf_token %}
	  <table>
		{{form.as_table}}
	  </table>
	  <br>
	  <input class="btn btn-dark" type="submit" value="수정하기">
  </form>
</div>

{% endblock %}