blog/urls.py
from django.urls import path, re_path
from blog import views


app_name = 'blog'
urlpatterns = [

    # Example: /blog/
    path('', views.PostLV.as_view(), name='index'),

    # Example: /blog/post/ (same as /blog/)
    path('post/', views.PostLV.as_view(), name='post_list'),

    # Example: /blog/post/django-example/
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),

    # Example: /blog/archive/
    path('archive/', views.PostAV.as_view(), name='post_archive'),

    # Example: /blog/archive/2019/
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),

    # Example: /blog/archive/2019/nov/
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),

    # Example: /blog/archive/2019/nov/10/
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),

    # Example: /blog/archive/today/
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),

    # Example: /blog/tag/
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),

    # Example: /blog/tag/tagname/
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),

    # Example: /blog/search/
    path('search/', views.SearchFormView.as_view(), name='search'),

    # Example: /blog/add/
    path('add/',
         views.PostCreateView.as_view(), name="add",
    ),

    # Example: /blog/change/
    path('change/',
         views.PostChangeLV.as_view(), name="change",
    ),

    # Example: /blog/99/update/
    path('<int:pk>/update/',
         views.PostUpdateView.as_view(), name="update",
    ),

    # Example: /blog/99/delete/
    path('<int:pk>/delete/',
         views.PostDeleteView.as_view(), name="delete",
    ),
]

forum/urls.py
from django.urls import path
from . import views
import forum.views

app_name='forum'
urlpatterns = [
    path('', views.forum_home, name='home'),
    path('new/', views.new, name='new'),
    path('detail/<int:forum_id>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('postcreate/', views.postcreate, name='postcreate'),
    path('update/<int:forum_id>/', views.update, name='update'),
    path('delete/<int:forum_id>/', views.delete, name='delete'),
    path('search', views.search, name='search'),
]

mate/urls.py
from django.urls import path

from mate import views

app_name = 'mate' 
urlpatterns = [
    path('', views.mate_home, name="home"),
    path('gallery', views.gallery, name="gallery"),
    path('quest', views.quest, name="quest"),
    path('questdone/<int:quest_id>', views.quest_done, name="quest-done"),
    path('upload/', views.upload, name='upload'),
	path('message/', views.send_message, name='send_message'),
]

moodtracker/urls.py
from django.urls import path

from moodtracker import views

app_name = 'moodtracker'
urlpatterns = [    
	path('', views.write_record, name='home'),
	path('record/<int:record_id>', views.view_record, name='view'), 
	path('write/', views.write_record, name='write'),
    path('create/',views.create_record, name='create'),
    path('analysis/', views.analysis, name='analysis'),
]

myprofile/urls.py
from django.urls import path

from myprofile import views

app_name = 'myprofile'
urlpatterns = [
    path('', views.profile_home, name='home'),
    path('detail/<int:profile_id>', views.profile_detail, name='detail'),
    path('upload/', views.upload, name='upload'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

import myprofile.views
import forum.views
import moodtracker.views
import mate.views
import therapy.views

from mysite import views
from mysite.views import HomeView, UserCreateView, UserCreateDoneTV


urlpatterns = [
    path('admin/', admin.site.urls),
    # shkim
    path('accounts/', include('django.contrib.auth.urls')), 
    path('accounts/register/', UserCreateView.as_view(), name='register'), 
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),

    path('', views.main, name='main'),
    path('student_analysis/<int:person_id>', views.student_analysis, name='student_analysis'),
    
    path('blog/', include('blog.urls')),
    path('forum/',include('forum.urls')),
    path('myprofile/',include('myprofile.urls'), name='myprofile'),
    path('moodtracker/', include('moodtracker.urls'), name='moodtracker'),
    path('mate/',include('mate.urls'), name='mate'),
    path('therapy/', include('therapy.urls'), name='therapy'),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

therapy/urls.py
from django.urls import path
from therapy import views

app_name = 'therapy'
urlpatterns = [
    path('', views.therapy, name='therapy'),
    path('result/', views.result, name='result'),
]

myprofile/models.py
from django.db import models
from django.contrib.auth.models import User

class MyProfile(models.Model):
    username = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='USERNAME', blank=True, null=True) # User 모델과 연결
    school = models.CharField(max_length=20)
    school_year = models.IntegerField(default=0)
    school_class = models.IntegerField(default=0)
    intro = models.CharField(max_length=200)
    profile_image = models.ImageField(upload_to='', default='default.png')

    def __str__(self):
        return "%s" % self.username # 유저 이름으로 구분
    
class ProfilePhoto(models.Model):
    myprofile = models.ForeignKey(MyProfile, on_delete=models.CASCADE, null=True)
    topic = models.CharField(max_length=30, default=0, null=True)
    image = models.ImageField(upload_to='', blank=True, null=True)

    def __str__(self):
        return "%s - %s" % (self.myprofile, self.id)


class MyClass(models.Model):
    #myprofile = models.ForeignKey(MyProfile, on_delete=models.CASCADE, null=True)
    myschool=models.CharField(max_length=20)
    hak = models.IntegerField(default=2)
    ban = models.IntegerField(default=6)
    class_intimacy=models.IntegerField(default=0)

myprofile/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

from .models import MyProfile, ProfilePhoto, MyClass
from django.contrib.auth.models import User

from django.contrib.auth.decorators import login_required

@login_required
def profile_home(request):
    user = request.user
    my = MyProfile.objects.get(username=user) # 현재 사용자의 프로필 정보를 불러온다.
    class_friends = MyProfile.objects.filter(school=my.school, school_year=my.school_year, school_class=my.school_class).exclude(username=user) # 같은 학교, 학년, 반인 친구들 프로필 정보
    my_class = MyClass.objects.get(myschool=my.school, hak=my.school_year, ban=my.school_class)
    class_score, class_score_text, class_level = class_achievement(my_class) # 학급 활성도
    
    item={
        'my' : my,
        'class_friends' : class_friends,
        'class_score' : class_score,
        'class_score_text' : class_score_text,
        'class_level' : class_level,
    }
    return render(request, 'myprofile/myprofile.html', item)

def class_achievement(my_class): # user가 속한 학교/학년/반이 작성한 게시판 글 수 등 받아서 계산 -> DB에 업데이트, 활성도 점수 index 함수로 보내기.
    a = my_class.class_intimacy
    if a >= 0 and a <= 20 :
        class_score_text = str(my_class.hak)+'학년 '+str(my_class.ban)+'반의 새싹이 피어났어요! 반 친구들과 함께 키워보아요!'
        class_level = 1
    elif a <= 40 :
        class_score_text = '벌써 이만큼 자랐네요! 나무가 될 때까지 더 키워볼까요?'
        class_level = 2
    elif a <= 60 :
        class_score_text = str(my_class.hak)+'학년 '+str(my_class.ban)+'반과 함께 무럭무럭 자라고 있어요! 잎이 많아질 때까지 조금 더 힘내볼까요?'
        class_level = 3
    elif a <= 80 :
        class_score_text = '우와, 나무가 정말 많이 자랐어요! 조만간 꽃이 피겠는걸요?'
        class_level = 4
    elif a <= 100 :
        class_score_text = '짝짝짝! '+str(my_class.hak)+'학년 '+str(my_class.ban)+'반의 활발한 소통이 꽃을 피웠어요!'
        class_level = 5 
    return a, class_score_text, class_level

@login_required
def profile_detail(request, profile_id):
    user = request.user # 현재 로그인한 사용자
    person = MyProfile.objects.get(pk=profile_id) # 보여줄 프로필의 주인
    person_images = ProfilePhoto.objects.filter(myprofile=person) # 프로필 주인이 올린 사진들
    
    if person.username==user : # 내 프로필일 때
        detail = 'my'
    else: # 다른 친구 프로필일 때
        detail = 'friend'
    
    # 이미지 모델에서 person.username으로 필터해온다.
    class_friends = MyProfile.objects.filter(school=person.school, school_year=person.school_year, school_class=person.school_class).exclude(username=user) # 같은 학교, 학년, 반인 친구들 프로필 정보

    item = {
        'person' : person,
        'person_images' : person_images,
        'detail' : detail,
        'class_friends' : class_friends,
    }
    return render(request, 'myprofile/profile_detail.html', item)

def upload(request):
    if(request.method == 'POST'):
        user = request.user
        user_id = MyProfile.objects.get(username=user)
        # name 속성이 imgs인 input 태그로부터 받은 파일들을 반복문을 통해 하나씩 가져온다 
        for img in request.FILES.getlist('imgs'):
            photo = ProfilePhoto() # ProfilePhoto 객체를 하나 생성한다.
            photo.myprofile = user_id # 외래키로 현재 생성한 MyProfile의 기본키를 참조한다.
            photo.image = img # imgs로부터 가져온 이미지 파일 하나를 저장한다.
            photo.topic = request.POST.get('topic')
            photo.save() # 데이터베이스에 저장
        return redirect('/myprofile/detail/' + str(user_id.id))
    else:
        return render(request, 'myprofile/myprofile.html')

myprofile/templates/myprofile/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}Be.com - 프로필{% endblock %}</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js"></script>
    {% block extra-style %}{% endblock %}
</head>



<body style="padding-top:90px;">
    <nav class="navbar navbar-expand-lg fixed-top" style="background-color: white;">
        <a class="navbar-brand mx-5 mb-0" href="{% url 'main' %}"><img src="{% static 'img/becom_logo.png' %}" width="140"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item mx-1 btn">
                    <a class="nav-link becom-nav" href="{% url 'main' %}">홈</a></li>
                <li class="nav-item mx-1 btn">
                    <a class="nav-link becom-nav link-active" href="{% url 'myprofile:home' %}">프로필</a></li>
                <li class="nav-item mx-1 btn">
                    <a class="nav-link becom-nav" href="{% url 'moodtracker:home' %}">감정 일기</a></li>
                <li class="nav-item mx-1 btn">
                    <a class="nav-link becom-nav" href="{% url 'mate:home' %}">짝꿍</a></li>
                <li class="nav-item mx-1 btn">
                    <a class="nav-link becom-nav" href="{% url 'forum:home' %}">게시판</a></li>

                
            </ul>

           
            <ul class="navbar-nav">
                <li class="nav-item" style="border: 2px solid #F99B0D;box-sizing:border-box;border-radius:10px;padding:12px 26px;">
                    <a class="register-therapy" href="{% url 'therapy:therapy' %}" style="text-decoration:none;color:#f99b0d;font-family: Noto Sans KR;font-weight: 500;font-size: 16px;">상담 신청하기</a>
                </li>
            </ul>

            <ul class="navbar-nav ml-5 mr-5">
                <li class="nav-item dropdown mx-1 btn " style="background-color: #ffffff;">
                    {% if user.is_active %}
                    <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" style="font-family: Noto Sans KR;font-size: 16px;color: #000000;">
                        <i class="fas fa-user"></i>&ensp;{% firstof user.get_short_name user.get_username %}님 환영합니다!&ensp;</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'logout' %}">로그아웃</a>
                        <a class="dropdown-item" href="{% url 'password_change' %}">비밀번호 변경</a>
                    </div>
                    {% else %}
                    <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">
                        <i class="fas fa-user"></i>&ensp;로그인 하세요&ensp;</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'login' %}">로그인</a>
                        <a class="dropdown-item" href="{% url 'register' %}">회원가입</a>
                    </div>
                    {% endif %}
                </li>
            </ul>

        </div>
    </nav>

    <div class="container">
        {% block content %}{% endblock %}
    </div>


    {% block footer %}{% endblock %}


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="https://kit.fontawesome.com/c998a172fe.js"></script>

    {% block extra-script %}{% endblock %}

</body>
</html>

myprofile/templates/myprofile/myprofile.html
{% extends 'myprofile/base.html' %}

{% load static %}
{% block extra-style %}<link rel="stylesheet" type="text/css" href="{% static 'css/myprofile_style.css' %}">{% endblock %}
{% block title %}Be.com - 프로필{% endblock %}

{% block content %}
<div class="container">
  <div class="col1">
    <div class="my-profile-home row">
      <div style="width:100%;">
        <div class="profile-title">내 프로필</div>
        <a href="{% url 'myprofile:detail' my.id %}" style="font-weight:bold; float:right; color:#7A7A7A; font-size:14px;">더보기</a>
      </div>
      <div class="my-profile">
        <img src="{{my.profile_image.url}}" width="150" height="150" style="border-radius:75px; border: 0.75px solid #C4C4C4;">
        <!--<div class="mb-1 text-muted">Nov 12</div>-->
        <div class="my-profile-intro">
          <b>이름</b> &nbsp; {{my.username}}<br>
          <b>학교</b> &nbsp; {{my.school}}<br>
          <b>학급</b> &nbsp; {{my.school_year}}학년 {{my.school_class}}반<br>
          <b>소개</b> &nbsp; {{my.intro}}</p>
        </div>
      </div>
    </div>
    <div class="class-achievement row">
      <div class="profile-title">우리 반 활성도</div>
      <div class="class-level">LEVEL{{class_level}}</div>
      <div class="class-score-text">{{class_score_text}}</div>
      <div class="class-level-img">
        {% if class_level == 1 %}
          <img src="{% static 'img/level1.png' %}" width="100px" alt="우리 반의 활성도">
        {% elif class_level == 2 %}
          <img src="{% static 'img/level2.png' %}" width="100px" alt="우리 반의 활성도">
        {% elif class_level == 3 %}
          <img src="{% static 'img/level3.png' %}" width="100px" alt="우리 반의 활성도">
        {% elif class_level == 4 %}
          <img src="{% static 'img/level4.png' %}" width="100px" alt="우리 반의 활성도">
        {% elif class_level == 5 %}
          <img src="{% static 'img/level5.png' %}" width="100px" alt="우리 반의 활성도">
        {% endif %}
      </div>
      <div class="progress">
        <div class="progress-bar" role="progressbar" aria-valuemin="0" aria-valuemax="100" style="width:{{class_score}}%">
          {{class_score}}%
        </div>
      </div>
    </div>
  </div>
    
  <div class="col2">
    <div class="friends">
      <div class="profile-title" style="margin:24px;">반 친구들</div>
      <div class="friends-list">
        {% for friend in class_friends.all %}
          <div class="friend-card">
            <a class="friend-card-a" href="{% url 'myprofile:detail' friend.id %}">
              <img src="{{friend.profile_image.url}}" width="80" height="80" style="border-radius:40px; border: 0.75px solid #C4C4C4;">
              <div style="font-size:14px; font-weight:500; line-height: 20px; margin-top:8px;">{{friend.username}}</div>
            </a>
            <div style="height: 1px; background-color: #f99b0d; margin:5px;"></div>
            <div style="font-weight: normal; font-size:12px;">{{friend.intro}}</div>
          </div>
        {% endfor %}
      </div>
      <!--<h1 class="display-4 font-italic">Title of a longer featured blog post</h1>
      <p class="lead my-3">Multiple lines of text that form the lede, informing new readers quickly and efficiently about what’s most interesting in this post’s contents.</p>
      <p class="lead mb-0"><a href="#" class="text-white font-weight-bold">Continue reading...</a></p>-->
    </div>
  </div>
</div>
   
{% endblock content %}

myprofile/templates/myprofile/profile_detail.html
{% extends 'myprofile/base.html' %}

{% load static %}
{% block extra-style %}<link rel="stylesheet" type="text/css" href="{% static 'css/myprofile_style.css' %}">{% endblock %}
{% block title %}Be.com - 프로필{% endblock %}

{% block content %}
<div class="container">
    <div class="go-home-button"><a href="{% url 'myprofile:home' %}" style="color:#5B5652;"><img src="{% static 'img/left_arrow.png' %}" height="16" style="float:left; margin-top:4px;">프로필 홈</a></div>
    <div class="col1">
        <div class="my-profile-detail">
            {% if detail == 'my' %}
                <div class="profile-title">내 프로필</div>
            {% elif detail == 'friend' %}
                <div class="profile-title">{{person.username}}님의 프로필</div>
            {% endif %}
            <div class="my-profile">
                <img src="{{person.profile_image.url}}" width="150" height="150" style="border-radius:75px; border: 0.75px solid #C4C4C4;">
                <!--<div class="mb-1 text-muted">Nov 12</div>-->
                <div class="my-profile-intro"><br><br>
                    <b>이름</b> &nbsp; {{person.username}}<br>
                    <b>학교</b> &nbsp; {{person.school}}<br>
                    <b>학급</b> &nbsp; {{person.school_year}}학년 {{person.school_class}}반<br>
                    <b>소개</b> &nbsp; {{person.intro}}<br><br><br></p>
                <!--<a href="#" class="stretched-link">Continue reading</a>-->
                </div>
            </div> 
        </div>
    </div>
    <div class="col2">
        <div class="profile-images">
            <div class="profile-title">나를 소개합니다</div>
                <div style="padding:12px;">
                    <!-- 내 프로필일 때만 사진 업로드 버튼 노출 -->
                    {% if detail == 'my' %}
                    <form  method="POST" action="{% url 'myprofile:upload' %}" enctype="multipart/form-data">
                        {% csrf_token %}
                        <!--
                        <select name="topic">
                            <option value="profile-image">프로필 사진</option>
                            <option value="favorite-spot">좋아하는 장소</option>
                            <option value="happiness">행복할 때</option>
                            <option value="friends">친구들과 함께</option>
                            <option value="favorite-movie">좋아하는 영화</option>
                            <option value="else">기타</option>
                        </select>
                        -->
                        <div class="filebox">
                            <input type="text" name="topic" size="10">
                            <input type="file" name="imgs" multiple>
                            <input type="submit" value="업로드" style="background:#f99b0d; color:white; border:none; border-radius:5px; padding:5px 12px;">
                        </div>
                    </form>
                    {% endif %}
                </div>
                <!-- 업로드한 이미지 삽입 -->
                <div class="profile-images-list">
                    {% for photo in person_images.all%}
                        <div class="profile-image">
                            <img src="{{photo.image.url}}" height="200" class="image" style="border-radius:10px;"><br>
                            <div class="overlay">
                                <div class="overlay-text">{{photo.topic}}</div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            <!--<h1 class="display-4 font-italic">Title of a longer featured blog post</h1>
            <p class="lead my-3">Multiple lines of text that form the lede, informing new readers quickly and efficiently about what’s most interesting in this post’s contents.</p>
            <p class="lead mb-0"><a href="#" class="text-white font-weight-bold">Continue reading...</a></p>-->
            </div>
        </div>
    </div>
</div>
   
{% endblock content %}
}